spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
              - x-requested-with
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS